# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - data: immucan_base
  - model: default
  - callbacks: default
  - logger: tensorboard
  - trainer: default
  - paths: default
  - extras: default
  - embeddings: default
  - classification: bareche
  - experiment: null
  - hydra: default
  - hparams_search: null
  - optional local: default
  - debug: null

task_name: "train"
tags: ["dev"]
train: True
validate: True
test: False
ckpt_path: null
seed: null
